# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'artifact1/pom.xml'
    goals: 'clean package'
    # ... other inputs

# 1. Copy the JAR and the POM to the staging directory
- task: CopyFiles@2
  inputs:
    SourceFolder: 'artifact1'
    Contents: |
      target/*.jar
      pom.xml
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

# 2. Publish from the staging directory instead of /target
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
